In [3]:
import numpy as np
a=np.array([9,28,13,32,8,23,12,25,13,27,13,27,13,26,8,31,15,26,9,23,-13,24,7,26,12,21,8,27,13,20,6,29,14,31,13,23,10,32,6,25,7,23,8,27,9,29,14,20,10,29,9,20,15,31,9,32,8,20,14,27,9,28,8,23,6,26,7,29,13,21,10,30,14,23,8,29,12,20,9,20,12,23,7,25,11,29,11,28,6,32,15,20,8,23,10,30,15,27,12,31,9,22,12,32,14,31,10,30,7,28,15,28,7,21,7,21,5,20,3,22,4,21,3,5,20,2,5,22,2,21,2,18,4,18,6,20,3,2,21,7,6,21,8,18,6,19,2,22,5,22,2,4,21,4,7,21,7,18,5,19,5,21,7,19,8,8,20,7,7,20,12,20,-10,20,10,20,7,20,9,71,18,8,11,21,8,22,9,20,9,20,9,19,12,11,19,8,8,20,7,18,8,21,9,19,11,19,10,7,20,7,10,18,12,22,7,21,9,20,8,18,10,11,20,10])

In [4]:
a.shape

(224,)

In [6]:
a

array([  9,  28,  13,  32,   8,  23,  12,  25,  13,  27,  13,  27,  13,
        26,   8,  31,  15,  26,   9,  23, -13,  24,   7,  26,  12,  21,
         8,  27,  13,  20,   6,  29,  14,  31,  13,  23,  10,  32,   6,
        25,   7,  23,   8,  27,   9,  29,  14,  20,  10,  29,   9,  20,
        15,  31,   9,  32,   8,  20,  14,  27,   9,  28,   8,  23,   6,
        26,   7,  29,  13,  21,  10,  30,  14,  23,   8,  29,  12,  20,
         9,  20,  12,  23,   7,  25,  11,  29,  11,  28,   6,  32,  15,
        20,   8,  23,  10,  30,  15,  27,  12,  31,   9,  22,  12,  32,
        14,  31,  10,  30,   7,  28,  15,  28,   7,  21,   7,  21,   5,
        20,   3,  22,   4,  21,   3,   5,  20,   2,   5,  22,   2,  21,
         2,  18,   4,  18,   6,  20,   3,   2,  21,   7,   6,  21,   8,
        18,   6,  19,   2,  22,   5,  22,   2,   4,  21,   4,   7,  21,
         7,  18,   5,  19,   5,  21,   7,  19,   8,   8,  20,   7,   7,
        20,  12,  20, -10,  20,  10,  20,   7,  20,   9,  71,  1

In [7]:
#Q1
b=a.reshape(4,4,7,2)
b

array([[[[  9,  28],
         [ 13,  32],
         [  8,  23],
         [ 12,  25],
         [ 13,  27],
         [ 13,  27],
         [ 13,  26]],

        [[  8,  31],
         [ 15,  26],
         [  9,  23],
         [-13,  24],
         [  7,  26],
         [ 12,  21],
         [  8,  27]],

        [[ 13,  20],
         [  6,  29],
         [ 14,  31],
         [ 13,  23],
         [ 10,  32],
         [  6,  25],
         [  7,  23]],

        [[  8,  27],
         [  9,  29],
         [ 14,  20],
         [ 10,  29],
         [  9,  20],
         [ 15,  31],
         [  9,  32]]],


       [[[  8,  20],
         [ 14,  27],
         [  9,  28],
         [  8,  23],
         [  6,  26],
         [  7,  29],
         [ 13,  21]],

        [[ 10,  30],
         [ 14,  23],
         [  8,  29],
         [ 12,  20],
         [  9,  20],
         [ 12,  23],
         [  7,  25]],

        [[ 11,  29],
         [ 11,  28],
         [  6,  32],
         [ 15,  20],
         [  8,  23],

In [8]:
#Q2
print(b.ndim)
print(b.shape)

4
(4, 4, 7, 2)


In [10]:
#Q3
print(b[:,0,:,:])

[[[  9  28]
  [ 13  32]
  [  8  23]
  [ 12  25]
  [ 13  27]
  [ 13  27]
  [ 13  26]]

 [[  8  20]
  [ 14  27]
  [  9  28]
  [  8  23]
  [  6  26]
  [  7  29]
  [ 13  21]]

 [[  7  21]
  [  7  21]
  [  5  20]
  [  3  22]
  [  4  21]
  [  3   5]
  [ 20   2]]

 [[  7  20]
  [ 12  20]
  [-10  20]
  [ 10  20]
  [  7  20]
  [  9  71]
  [ 18   8]]]


In [12]:
#Q4
print(b[:,:,1,:])

[[[13 32]
  [15 26]
  [ 6 29]
  [ 9 29]]

 [[14 27]
  [14 23]
  [11 28]
  [ 9 22]]

 [[ 7 21]
  [ 2 21]
  [ 8 18]
  [ 7 18]]

 [[12 20]
  [ 8 22]
  [ 7 18]
  [12 22]]]


In [15]:
#Q5
print(b[1:4:2,:,:,1])

[[[20 27 28 23 26 29 21]
  [30 23 29 20 20 23 25]
  [29 28 32 20 23 30 27]
  [31 22 32 31 30 28 28]]

 [[20 20 20 20 20 71  8]
  [21 22 20 20 19 11  8]
  [20 18 21 19 19  7  7]
  [18 22 21 20 18 11 10]]]


In [40]:
#Q6
ni = np.array(b[0, :, :, 0] < 8)
print(ni)
i=0
j=0
for i in range(4):
    for j in range(7):
        if (ni[i,j]=="true"):
            print("week:",i,"\nday:",j)
        j+=1
    i+=1  


[[False False False False False False False]
 [False False False  True  True False False]
 [False  True False False False  True  True]
 [False False False False False False False]]


In [42]:
#Q12
winter = b[0:4, :, :, 1] 
w = np.mean(winter)
w

21.839285714285715

In [47]:
#Q13
dec = b[1, :, :, 0] 
print(dec)
wd = np.mean(dec, axis=1)
wd

[[ 8 14  9  8  6  7 13]
 [10 14  8 12  9 12  7]
 [11 11  6 15  8 10 15]
 [12  9 12 14 10  7 15]]


array([ 9.28571429, 10.28571429, 10.85714286, 11.28571429])

In [50]:
#Q14
dec_jan = np.concatenate((b[1, :, :, :], b[2, :, :, :]), )


overall_avg_temp = np.mean(dec_jan)
overall_avg_temp

14.919642857142858

In [51]:
#Q15
dec_jan_min_temps = np.concatenate((b[1, :, :, 0], b[2, :, :, 0]), axis=0)
least_temp = np.min(dec_jan_min_temps)
least_temp_index = np.argmin(dec_jan_min_temps)

# Determine the month, week, and day for the least temperature
month, day_week_index, day = np.unravel_index(least_temp_index, (2, 4, 7))
if month == 0:
    month_name = "December"
else:
    month_name = "January"
week = day_week_index + 1

print(f"Least temperature: {least_temp:.2f}°C")
print(f"Date of occurrence: Month: {month_name}, Week: {week}, Day: {day + 1}")

Least temperature: 2.00°C
Date of occurrence: Month: January, Week: 2, Day: 2


In [52]:
#Q16
feb_max_temps = b[3, :, :, 1] 


max_temp_feb = np.max(feb_max_temps)
max_temp_feb_index = np.unravel_index(np.argmax(feb_max_temps), feb_max_temps.shape)


month = 3
week, day = max_temp_feb_index

print(f"Max temperature in February: {max_temp_feb:.2f}°C")
print(f"Date of occurrence: Month: February, Week: {week + 1}, Day: {day + 1}")

Max temperature in February: 71.00°C
Date of occurrence: Month: February, Week: 1, Day: 6


In [53]:
#Q17

nov_max_temps = b[0, :, :, 1]

avg_max_temp_nov = np.mean(nov_max_temps)

days_below_avg_temp = np.where(nov_max_temps < avg_max_temp_nov)


print("Days in November with max temp below average:")
for day in days_below_avg_temp[0]:
    print(f"Day {day + 1}")

Days in November with max temp below average:
Day 1
Day 1
Day 1
Day 2
Day 2
Day 2
Day 2
Day 2
Day 3
Day 3
Day 3
Day 3
Day 4
Day 4


In [55]:
#Q18
b_f = (b * 9/5) + 32

print("Temperature Data in Fahrenheit:")
print(b_f)

Temperature Data in Fahrenheit:
[[[[ 48.2  82.4]
   [ 55.4  89.6]
   [ 46.4  73.4]
   [ 53.6  77. ]
   [ 55.4  80.6]
   [ 55.4  80.6]
   [ 55.4  78.8]]

  [[ 46.4  87.8]
   [ 59.   78.8]
   [ 48.2  73.4]
   [  8.6  75.2]
   [ 44.6  78.8]
   [ 53.6  69.8]
   [ 46.4  80.6]]

  [[ 55.4  68. ]
   [ 42.8  84.2]
   [ 57.2  87.8]
   [ 55.4  73.4]
   [ 50.   89.6]
   [ 42.8  77. ]
   [ 44.6  73.4]]

  [[ 46.4  80.6]
   [ 48.2  84.2]
   [ 57.2  68. ]
   [ 50.   84.2]
   [ 48.2  68. ]
   [ 59.   87.8]
   [ 48.2  89.6]]]


 [[[ 46.4  68. ]
   [ 57.2  80.6]
   [ 48.2  82.4]
   [ 46.4  73.4]
   [ 42.8  78.8]
   [ 44.6  84.2]
   [ 55.4  69.8]]

  [[ 50.   86. ]
   [ 57.2  73.4]
   [ 46.4  84.2]
   [ 53.6  68. ]
   [ 48.2  68. ]
   [ 53.6  73.4]
   [ 44.6  77. ]]

  [[ 51.8  84.2]
   [ 51.8  82.4]
   [ 42.8  89.6]
   [ 59.   68. ]
   [ 46.4  73.4]
   [ 50.   86. ]
   [ 59.   80.6]]

  [[ 53.6  87.8]
   [ 48.2  71.6]
   [ 53.6  89.6]
   [ 57.2  87.8]
   [ 50.   86. ]
   [ 44.6  82.4]
   [ 59.   82.4]]

In [56]:
#Q19

dec_avg_temps = b[1, :, :, :].mean(axis=(1, 2))


sorted_data_dec = b[dec_avg_temps.argsort()[::-1]]

print("Sorted Data for December:")
print(sorted_data_dec)

Sorted Data for December:
[[[[  7  20]
   [ 12  20]
   [-10  20]
   [ 10  20]
   [  7  20]
   [  9  71]
   [ 18   8]]

  [[ 11  21]
   [  8  22]
   [  9  20]
   [  9  20]
   [  9  19]
   [ 12  11]
   [ 19   8]]

  [[  8  20]
   [  7  18]
   [  8  21]
   [  9  19]
   [ 11  19]
   [ 10   7]
   [ 20   7]]

  [[ 10  18]
   [ 12  22]
   [  7  21]
   [  9  20]
   [  8  18]
   [ 10  11]
   [ 20  10]]]


 [[[  7  21]
   [  7  21]
   [  5  20]
   [  3  22]
   [  4  21]
   [  3   5]
   [ 20   2]]

  [[  5  22]
   [  2  21]
   [  2  18]
   [  4  18]
   [  6  20]
   [  3   2]
   [ 21   7]]

  [[  6  21]
   [  8  18]
   [  6  19]
   [  2  22]
   [  5  22]
   [  2   4]
   [ 21   4]]

  [[  7  21]
   [  7  18]
   [  5  19]
   [  5  21]
   [  7  19]
   [  8   8]
   [ 20   7]]]


 [[[  8  20]
   [ 14  27]
   [  9  28]
   [  8  23]
   [  6  26]
   [  7  29]
   [ 13  21]]

  [[ 10  30]
   [ 14  23]
   [  8  29]
   [ 12  20]
   [  9  20]
   [ 12  23]
   [  7  25]]

  [[ 11  29]
   [ 11  28]
   [  6  32]
 

In [58]:
#Q24
# Calculate the difference between min temp of two consecutive days for each month
min_temp_diff_per_month = b[:, :, 1:, 0] - b[:, :, :-1, 0]

print("Temperature Difference Between Min Temp of Consecutive Days for Each Month:")
print(min_temp_diff_per_month)

Temperature Difference Between Min Temp of Consecutive Days for Each Month:
[[[  4  -5   4   1   0   0]
  [  7  -6 -22  20   5  -4]
  [ -7   8  -1  -3  -4   1]
  [  1   5  -4  -1   6  -6]]

 [[  6  -5  -1  -2   1   6]
  [  4  -6   4  -3   3  -5]
  [  0  -5   9  -7   2   5]
  [ -3   3   2  -4  -3   8]]

 [[  0  -2  -2   1  -1  17]
  [ -3   0   2   2  -3  18]
  [  2  -2  -4   3  -3  19]
  [  0  -2   0   2   1  12]]

 [[  5 -22  20  -3   2   9]
  [ -3   1   0   0   3   7]
  [ -1   1   1   2  -1  10]
  [  2  -5   2  -1   2  10]]]
